
FROM node:18-alpine AS builder

WORKDIR /app

COPY spa/package*.json ./
RUN npm install --production
COPY spa .
FROM node:18-alpine
ENV NODE_ENV=production \
    PORT=4000
WORKDIR /app
COPY --from=builder /app /app
EXPOSE $PORT
ENTRYPOINT ["npm", "start"]